### ISSUE TITLE
rabl-rails assumes any object that respond to `each` is a collection

### ISSUE THREAD

**Issue by jrunning** [ccocchi/rabl-rails#55]
I'd like to use rabl-rails to render an object, but since the object responds to `each`, RablRails::Renderers::Base tries to render it as a collection. Here's code that reproduces the problem:

``` ruby
# app/views/controllers/config_controller.rb
class ConfigController < ApplicationController
  respond_to :json

  def show
    struct = Struct.new(:foo)
    @config = struct.new("bar")
  end
end
```

``` ruby
# app/views/config/show.json.rabl
object :@config
attribute :foo
```

I would expect this to render `{"foo":"bar"}` since `@config.foo` returns `"bar"`. However, because `@config` responds to `each`, `Renderers::Base#render` [calls `render_collection` on it instead of `render_resource`](https://github.com/ccocchi/rabl-rails/blob/82cd9972aa82470b586b9dce01f37f71d203ed55/lib/rabl-rails/renderers/base.rb#L32-L33), yielding an error:

``` text
undefined method `foo' for "bar":String
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:68:in `block in render_resource'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:64:in `each'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:64:in `inject'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:64:in `render_resource'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:116:in `block in render_collection'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:116:in `each'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:116:in `map'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:116:in `render_collection'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:32:in `block in render'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:55:in `render_with_cache'
  (gem) rabl-rails-0.3.3/lib/rabl-rails/renderers/base.rb:31:in `render'
  ...
```

(You can see the complete backtrace here: https://gist.github.com/jrunning/9279963)

This might seem like a contrived example, but I ran into it in a real scenario (I was trying to render attributes of an ActiveSupport::OrderedOptions rather than a struct). The same issue would manifest if someone defined `each` on an ActiveRecord model.

I'm not sure what the best solution is. Perhaps `object` could take an option that would explicitly tell it not to render the object as a collection?

For now my only option seems to be falling back to the regular rabl gem, which lacks some of the Railsy niceties of rabl-rails.

**Comment by pkuykendall** [comment]
I found good results with changing the ```collection?``` helper to include a class check for ```Enumerable ```

```ruby
resource && resource.respond_to?(:each) && resource.kind_of?(Enumerable) &&
        klass.ancestors.none? { |a| RablRails.configuration.non_collection_classes.include? a.name }
```

What are your thoughts? @ccocchi

**Comment by myxrome** [comment]
it is not compatible with [sequel-rails](https://github.com/TalentBox/sequel-rails). the code 
`partial "path/to/partial", object: object`
will fail on
https://github.com/ccocchi/rabl-rails/blob/master/lib/rabl-rails/visitors/to_hash.rb#L127
because of sequel model does respond to `each` method. and it does not respond to `map` method.
could you please fix it.

**Comment by ccocchi** [comment]
Hello,

I don't understand what your problem is. If a sequel model (I'm assuming it is an equivalent of `ActiveRecord::Base`) does not respond to the `each` method, it won't be treated as a collection but as an object, which is the expected behavior.

Where am I mistaken?
