### ISSUE TITLE
Rails 4.2

### ISSUE THREAD

**Issue by dustineichler** [ccocchi/rabl-rails#72]
If you can't get this to work in Rails 4.2. Adding require: false to your Gemfile resolves this issue. Your object appears nil the template otherwise.

**Comment by BenMorganIO** [comment]
:+1:

**Comment by lephyrius** [comment]
:+1: 
I'm just wondering if it is possible to use this without the responders gem? Shouldn't it be an dependency for rabl-rails?

**Comment by acaron** [comment]
+ 1
Can't make the `respond_with` work with rails 4.2.1 even with the `require: false`. Also, you need to add `require 'rabl-rails'` before the configuration!

**Comment by itkin** [comment]
:+1: thanks @acaron, `require 'rabl-rails' ` into an initializer made it work

**Comment by ccocchi** [comment]
Fixed in `0.4.3`. Custom responder will be removed starting version `0.5.0` of this gem.
