### ISSUE TITLE
Not being able to use a cache key in rabl generated by controller. 

### ISSUE THREAD

**Issue by pamio** [ccocchi/rabl-rails#81]
Hi,
I've been using rabl-rails for sometime now and its great. But I'm not able to use a cache key generated by controller in the rabl template. 

Here is the code

```
def some_action
   @cache_key = "#{params[:x]}-#{params[:y]}"
end

some_action.json.rabl

object :@brand, root: false
cache {|b| @cache_key}
```

Also I can't seem to be able to access the params hash in the rabl template. Is this intended ? How can I achieve this ?

Thanks in advance.

**Comment by ccocchi** [comment]
Hello,

Sadly the `cache` directive cannot is not evaluated in the context of the controller so you cannot access any variable from there nor the `params` hash. It was made only to have the object or collection available within the block.

**Comment by pamio** [comment]
Thanks for the clarification.
