### ISSUE TITLE
undefined method for nil:NilClass on Rails 5.0.1

### ISSUE THREAD

**Issue by razvanmitre** [ccocchi/rabl-rails#87]
Hello,

I am trying to switch over from rabl, but I receive this error on all templates. On rabl it works fine.

Take this template for example, it just returns some ids.
```
collection @properties
attributes :id
```

I am also using oj gem on Rails 5.0.1.

Do I need to do anything else?

Thanks

**Comment by MrWilhelm** [comment]
I think you should make `collection :@properties`, with symbol.

**Comment by jr180180** [comment]
First off, thank you @razvanmitre for mentioning this. And, second, thanks a ton @MrWilhelm for mentioning the colon there to make it a symbol. I kept running into this issue with the following and you've saved me a TON of time.

Here's what I had:

``` ruby
object @example
attributes :id
```

adding that colon fixed it. 

``` ruby
object :@example
attributes :id
```

BOOM! Thanks guys!
